#!/usr/bin/env bash
# uses ssh to connect to your server using the
# private key ~/.ssh/school with the user ubuntu
if (($# < 3)); then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE=$1
IP=$2
USERNAME=$3
PRV_KEY=$4

if (($# == 3)); then
    scp -o StrictHostKeyChecking=no "$FILE" "$USERNAME"@"$IP":~/
else
    scp -o StrictHostKeyChecking=no -i "$PRV_KEY" "$FILE" "$USERNAME"@"$IP":~/
fi
