#!/usr/bin/env bash
# Nginx Config: 301 Redirect from /redirect_me to /redirected_page.html

# Checking if Nginx is installed
if ! command -v nginx &> /dev/null; then
    sudo apt-get update
    sudo apt-get -y install nginx
fi

# Create a sample index file
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

# Define redirection configuration
line_number=53
text_to_insert="location /redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}"

# Insert the redirection configuration into Nginx default site configuration
sudo sed -i "${line_number}a$text_to_insert" /etc/nginx/sites-available/default

# Reload Nginx configuration
sudo service nginx start
