#!/usr/bin/env bash
# Nginx Config: 301 Redirect from /redirect_me to /redirected_page.html

# Checking if Nginx is installed
if ! command -v nginx &> /dev/null; then
    sudo apt-get update
    sudo apt-get -y install nginx
fi

# Create a sample index file
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

# Define redirection configuration
line_number=53
text_to_insert="location /redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}"

# Check if the redirection configuration already exists
if ! sudo grep -q "location /redirect_me {" /etc/nginx/sites-available/default; then
    # Insert the redirection configuration into Nginx default site configuration
    sudo sed -i "${line_number}a$text_to_insert" /etc/nginx/sites-available/default
fi

# Check if the custom error page configuration already exists
if ! sudo grep -q "error_page 404 /custom_404.html;" /etc/nginx/sites-enabled/default; then
    sudo sed -i '/server_name _;/a \
    \ \ \ error_page 404 /custom_404.html;\n\
    \ \ \ location = /custom_404.html {\n\
    \ \ \ \ \ root /usr/share/nginx/html;\n\
    \ \ \ \ \ internal;\n\
    \ \ \ }' /etc/nginx/sites-enabled/default
fi

# Check if the custom 404.html file already contains the desired content
if ! sudo grep -q "Ceci n'est pas une page" /usr/share/nginx/html/custom_404.html; then
    # Add the desired content to the custom 404.html file
    echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html > /dev/null
fi

# Reload Nginx configuration
sudo service nginx start
