#!/usr/bin/env bash
# Nginx Config: 301 Redirect from /redirect_me to /redirected_page.html

# Checking if Nginx is installed
if ! command -v nginx &> /dev/null; then
    sudo apt-get update
    sudo apt-get -y install nginx
fi

# Create a sample index file
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

# Define redirection configuration
line_number=53
text_to_insert="location /redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}"

# Insert the redirection configuration into Nginx default site configuration
sudo sed -i "${line_number}a$text_to_insert" /etc/nginx/sites-available/default

sudo sed -i '/server_name _;/a \
\ \ \ error_page 404 /custom_404.html;\n\
\ \ \ location = /custom_404.html {\n\
\ \ \ \ \ root /usr/share/nginx/html;\n\
\ \ \ \ \ internal;\n\
\ \ \ }' /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html > /dev/null

sudo sed -i "/include \/etc\/nginx\/sites-enabled\/\*;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf

# Reload Nginx configuration
sudo service nginx restart
