#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
# On the 9th iteration, displays "Hi" before "Best School".
i=1
while((i <= 10))
do
    if ((i != 9))
    then
        echo "Best School"
    else
        echo "Hi"
    fi
    ((i++))
done
