#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes.
#   Displays hours from 0 to 12
#   Displays minutes from 1 to 59
hour=0
while ((hour <= 12))
do
    echo "Hour: $hour"
    min=1
    while ((min <= 59))
    do
        echo $min
        ((min++))
    done
    ((hour++))
done