#!/usr/bin/env bash
# Fix web server to run Nginx as the nginx user listening on port 8080.
chown nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
